import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Providers from '@/components/Providers';
import { Toaster } from 'react-hot-toast';

// const geistSans = localFont({
//   src: './fonts/Inter-Regular.ttf',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });

const teachers = localFont({
  src: [
    {
      path: './fonts/Teachers-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Teachers-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Teachers-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Teachers-Bold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: './fonts/Teachers-ExtraBold.ttf',
      weight: '900',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Learn ChatPDF',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <Providers>
        <html lang="en">
         
          <body className={`${teachers.className} antialiased`}>
            {children}
          </body>
          <Toaster />
        </html>
      </Providers>
    </ClerkProvider>
  );
}
